export default {
  test: 'Test',
  add: 'New addition',
  edit: 'Edit',
  delete: 'Delete',
  cancel: 'Cancel',
  save: 'Preserve',
  confirm: 'Confirm',
  close: 'Close',
  update: 'Update',
  search: 'Search',
  reset: 'Reset',
  copy: 'Copy',
  login: 'Login',
  logout: 'Quit',
  signup: 'Register',
  profile: 'Personal Center',
  setting: 'Set up',
  menu: 'Menu',
  home: 'Home page',
  example: 'example page',
  username: 'User name',
  password: 'Password',
  email: 'Mailbox',
  phone: 'Mobile phone number',
  sex: 'Gender',
  birthday: 'Birthday',
  nickname: 'Nickname',
  remark: 'Remarks',
  status: 'State',
  role: 'Role',
  permission: 'Authority',
  about: 'About',
  version: 'Version',
  copyright: 'Copyright',
  user_manage: 'User management ',
  role_manage: 'Role management',
  permission_manage: 'Permission management',
  menu_manage: 'Menu management',
  log_manage: 'Log management',
  system_manage: 'System management',
  system_config: 'System configuration',
  module: 'Module',
  keyword: 'Keyword',
  pagination: 'Paging',
  page_size: 'Number of displayed items per page',
  current_page: 'Current page',
  page_total: 'PageCount ',
  asset_manage: 'Asset management',
  asset: 'Asset',
  asset_type: 'Asset type',
  asset_category: 'Asset classification',
  asset_status: 'Asset status',
  asset_list: 'Asset List',
  asset_add: 'Add assets',
  asset_edit: 'Edit Assets',
  asset_delete: 'Delete Asset',
  asset_detail: 'Asset details',
  asset_log: 'Asset log',
  report: 'Report forms',
  report_manage: 'Report Management',
  report_list: 'Report List',
  report_add: 'Add Report',
  report_edit: 'Edit Report',
  report_delete: 'Delete Report',
  report_detail: 'Report details',
  report_log: 'Report logs',
  dashboard: 'Instrument panel',
  dashboard_manage: 'Dashboard management',
  dashboard_list: 'Dashboard List',
  dashboard_add: 'Add dashboard',
  dashboard_edit: 'Edit dashboard',
  dashboard_delete: 'Delete dashboard',
  dashboard_detail: 'Instrument panel details',
  dashboard_log: 'Dashboard logs'
};
