export default {
  tuiChuDengLu: 'Quit',
  geRenXinXi: 'Personal Information',
  zhiQiFuHuaQi: 'Zhiqi vue3 incubator system',
  genericTypicalPage: 'Generic typical page',
  lieBiaoYe: 'List page',
  biaoDanYe: 'Form page',
  xiangQingYe: 'Details page',
  peiZhiYe: 'Configuration page',
  daPingZiDingYi: 'Large screen customization',
  gongZuoTaiZiDingYi: 'Workbench customization',
  baoBiaoZiDingYi: 'Report customization',
  tuKeShiHuaChengXian: 'Graphic visualization',
  tuBianJiQi: 'Graph editor',
  liuChengBianPai: 'Flow choreography',
  xiTongSheZhi: 'System setting',
  zhuTiPeiZhiYe: 'Topic configuration page',
  dengLuPeiZhiYe: 'Login configuration page',
  zaiXianShengJi: 'Online upgrade',
  yongHuYinDao: 'User guidance',
  bangZhuWenDang: 'Help document',
  ruMenYinDao: 'Introductory guide',
  caiDanMingCheng:'Menu name',
  qingShuRuCaiDanMingCheng:'Please enter a menu name',
  caiDanTiXi:'Menu system',
  qingShuRuCaiDanTiXi:'Please select a menu system',
  suoShuYiJiCaiDan: 'Subordinate level menu',
  qingXuanZeSuoShuYiJiCaiDan: 'Please select the Level 1 menu',
  fangWenFangShi: 'Access mode',
  xinKaiYeMian: 'New page',
  neiQianYeMian: 'Embedded page',
  baoLiuYuanCaiDan: 'Keep the original menu',
  guanLianURL: 'Associated URL',
  qingShuRuYeMianDiZhi: 'Please enter the page address',
  caiDanGuanLianURL: 'Please enter the URL associated with the menu',
  yeMianCanShu: 'Page parameter',
  caiDanXianYinCanShu: 'Please enter the menu implicit parameters of the corresponding product',
  gongZuoTai: 'workbench',
  jiChuBiaoDan: 'Base form',
  jiChuXiangQing: 'Basic details',
  jiChuPeiZhi: 'Basic configuration',
  moRenXuanXiang1: 'Default option 1',
  moRenXuanXiang2: 'Default option 2',
  moRenXuanXiang3: 'Default option 3',
  miMaAnQuanSheZhi: 'Password security settings',
  peiZhiMiMaAnQuanYaoQiu:'Configure password security requirements to prevent weak passwords',
  zuiXiaoMiMaChangDu: 'The minimum password length is set to',
  zuiDaMiMaChangDu: 'The maximum password length is set to',
  wei:'digit',
  jianYiSheZhi: 'Suggest setting a password change every',
  tianGengHuanYiCiMiMa: 'days',
  jianYiMei3GeYueGengXinYiCi: 'Recommended to be updated every 3 months',
  tiShi: 'Tips',
  dengLuAnQuanSheZhi: 'Login security Settings',
  xianZhiYongHuDengLuFangShi: 'Limits user login failure frequency and lock mode to protect system login security',
  miaoZhiNei: 'description The number of failed login attempts within seconds exceeded',
  ciSuoDing: 'Time, lock the',
  zhangHu: 'account',
  suoDingZhangHu: 'Locked account',
  chaoShiSheZhi: 'Timeout setting',
  baoHuYongHuShuJuAnQuan: 'Protect user data security and prevent information leakage',
  fenZhongZhiNeiYongHuWuCaoZuo: 'If the user does not perform any operation within minutes, the system logs out',
  jianYi: 'Suggestion',
  ciPanChuCunSheZhi: 'Disk storage Settings',
  ziDongQingLiCiPan: 'The disk is automatically cleared to prevent disk overload',
  dangCiPanKongJianChaoGuo: 'When the disk storage space exceeds',
  shuJuJiangZiDongXunHuanFuGai: 'Data is automatically cycled over and an alarm is generated',
  shuZi: 'figure',
  ziMuDaXiaoXie: 'Letters（case）',
  teShuZiFu: 'Special character',
  jinZhiChiEXCELGeShiWenJian: 'Only EXCEL files are supported',
  moRenBiaoQian: 'Default tag',
  zaiXian: 'online',
  miaoBianAnNiu: 'Stroke button',
  zuJianLeiXing: 'Component type',
  liuLiangTanZhen: 'Flow probe(APT)',
  zhuCeShiJian: 'Registration time',
  benRiShangSongTiaoShu: 'Number of items sent today',
  weiYiBiaoShi: 'Unique identification',
  ruanJianBanBen: 'Software version',
  xuKeZheng: 'licence',
  tiao: 'article',
  zhengShi: 'Formal',
  daoQi: 'expire',
  sheBei: 'Device IP',
  guiZeBanBen: 'Rule version',
  danWei: 'unit',
  gengDuoXinXi: 'More information',
  ziChanBianHao: 'Asset number',
  shiYongZhuangTai: 'Use condition',
  shiYongZhong: 'In use',
  shiYongRen: 'user',
  miaoShuXinXi: 'Descriptive information',
  guoChanHua: 'localization',
  puTong: 'Normal',
  renWuJiLu: 'Task record',
  diZhi: 'Address',
  gaoFengXian: 'High risk',
  zhongFengXian: 'Medium risk',
  diFengXian: 'Low risk',
  yunXuFangWen: 'Allow access',
  mingLingZuDuan: 'Command blocking',
  xinJian: 'New build',
  daoChu: 'Export',
  zhongDianGuanZhu: 'Focus on',
  quXiaoGuanZhu: 'Unfollow',
  xiangQing: 'Details',
  shuRuKuangWenBen: 'Input Box Text',
  xuanZeQi: 'Selector',
  xuanZeXiang1: 'Option 1',
  xuanZeXiang2: 'Option 2',
  riQi: 'Date',
  qingXuanZe: 'Please select',
  riQiFanWei: 'Date range',
  kaiShiShiJian: 'Start time',
  jieShuShiJian: 'End time',
  xiangMuMingCheng: 'Project Name',
  suoShuZuZhi: 'Affiliated organization',
  suoShuLeiBie: 'Category',
  caoZuo: 'Operation',
  moRenXuanXiang: 'Default option',
  yiXuanXuanXiang: 'Selected options',
  gongNengKaiFaZhong: 'Under development, stay tuned~',
  zhangHaoMiMaDengLu: 'Log in with account and password',
  miMaBuDeXiaoYu: 'The password must not be less than 6 characters',
  yanZhengMa: 'Captcha',
  shouJiYanZhengMaDengLu: 'Log in with mobile phone verification code',
  shouJiHaoMa: 'Phone number',
  huaKuaiYanZheng: 'Slider verification',
  zhuCeZhangHao: 'Register an account',
  shouJiYanZhengMa: 'Phone verification code',
  queRenMiMa: 'Confirm password',
  xinMiMa: 'New password',
  dingDingSaoMa: 'DingTalk QR code scan login',
  weiXinSaoMa: 'Scan the QR code to log in with WeChat',
  zhaoHuiMiMa: 'Retrieve password',
  zhuTiFengGe: 'Theme style',
  shenSe: 'Dark color',
  qianSe: 'Light color',
  dengLuYeBeiJing: 'Login page background',
  tuPian: 'Picture',
  shiPin: 'video',
  shangChuan: 'Upload',
  huiFuChuChangTuPian: 'Restore factory images',
  zhiNengShangChuan: 'Can only upload',
  wenJian: 'File',
  qieBuChaoGuo: 'and not exceed',
  jianYiTuPianBiLi: 'Suggest image ratio',
  fengMian: 'Cover',
  shiPinHeTuPianYiZhi: 'Keep the dimensions of the video and images consistent',
  jianYiBiLi: 'Suggested ratio',
  huiFuChuChangShiPin: 'Restore factory video',
  dengLuYe: 'Login Page ',
  wenzi: 'Text',
  shenSeBeiJingJianYiShiYong: 'Dark background suggests using a white logo',
  xianShiDuoYuYanQieHuan: 'Display multilingual switching',
  xuanChuanBiaoYu: 'Slogan',
  gongSiMingCheng: 'Company Name',
  pingTaiBanQuanXinXi: 'Platform Copyright Information',
  gongAnJiGuanBeiAnXinXi: 'Recorded information with the public security bureau',
  gongAnJiGuanBeiAnChaoLianDiZhi: 'Hyperlink address for public security organ filing information',
  ICPbeiAnXinXi: 'ICP filing information',
  ICPbeiAnChaoLianDiZhi: 'ICP filing hyperlink address',
  shuaXin: 'Refresh',
  quanPing: 'Full screen',
  huiFuChuChangSheZhi:'Reset to factory settings',
  yingYongDangQianSheZhi:'Apply the current settings',
  xinZhuTiFengGeTiShi:'The new theme style will cover all account custom styles, are you sure you want to save the new theme style and apply it to all account systems?',
  wenJianGeShiBuWei:'The file format is not',
  wenJianDaXiaoChaoGuo:'File size exceeds',
  moRenZhuTi: 'Default theme',
  moRenZhuTiSe: 'Default theme color',
  daoHangSheZhi: 'Navigation settings',
  daoHangBuJu: 'Navigation Layout',
  qiTaSheZhi: 'Other settings',
  shengChengYeMianQianTaoCanShu:'Generate page nested parameters',
  yingYongDangQianZhuTi:'Apply the current theme',
  shengChengYeMianQianTaoCanShuTanChuangWenAn:'Copy the new style of the page and separate the parameters for the menu area and content area of the page. If the menu needs to be hidden when embedded, please include this parameter.',
  caiDanXianYinCanShu2:'Menu display and hide parameters',
  fuZhiCanShu: 'Copy parameters',
  queRen: 'Confirm',
  fuZhiChengGongWenAn: 'Copy successful, please paste the parameters into the corresponding form of the new menu.',
  dianJiDaoXiaYiBu: 'Click to proceed to the next step',
  ziDingYiXiaYiBuWenZi: 'Customize the next step text',
  gaoLiangQuYuKePeiZhi: 'Highlight areas can be configured',
  moRenWeiBangDingYuanSuQuYu:'Default is to highlight the bound element area, you can set the padding',
  zheZhaoCengZhiChiGuanBi:'Mask layer supports turning off',
  gongXiNiWanChengYinDao:'Congratulations, you have completed the demo guide',
  lingYiGeYeMianYinDao:'Another page guide',
  shangYiBuHaHa:'Go back a step haha',
  quLingYiGeYeMian:'Go to another page',
  yiQiShangShou:'Welcome! Come and join me to get started quickly',
  cuiLueDedemo:'This is just a rough demo',
  huiXuHuiWanShan:'I will improve it later',
  jingQingQiDai:'Please understand, everyone.',
  keNengXuYaoFanHuiShangYiCi:'There might be a need to return to the previous page to guide the situation',
  xiaYiBu:'Next step',
  wanCheng:'Completed',
  shangYiBu:'Go back one step',
  woFuZeShiJianDeJiBieFenPei:'I am responsible for the level assignment of events.',
  gaoWei:'High risk',
  zhongWei:'Medium risk',
  diWei:'lowly',
  woFuZeShiJianZhuangTaiFenBu:'I am responsible for the distribution of event statuses',
  huoDongZhong:'During the event',
  yiGuanBi:'Closed',
  yiChaoShi:'Timed out',
  cuoWu:'Error',
  woFuZeShiJianShuLiangQuShi:'I am responsible for the trend of event quantities.',
  moRen:'Default',
  ziDingYi:'Customize',
  sheZhiPianHao:'Set preferences',
  woCanYuDeShiJianZongShu:'The total number of events I am involved in',
  woFuZeDeShiJianZongShu:'The total number of events I am responsible for',
  woFuZeShiJianDePingJunChuLiShiJian:'I am responsible for the average processing time of events',
  jian:'piece',
  shi:'Hour',
  fen:'minute',
  miao:'second',
  woFuZeDeShiJianGuanBiLv:'My event closure rate',
  gengDuo:'More',
  bangZhuWenDangBiaoTi:'The Importance and Function of Help Documentation',
  bangZhuWenDangWenAn1:'Help documentation is a vital resource that provides users with detailed information and guidance on how to use specific software, applications, services, or products. The functions of help documentation are mainly reflected in the following aspects:',
  bangZhuWenDangWenAnBiaoTi1:'Quick Start:',
  bangZhuWenDangWenAnNeiNong1:'Help documents typically include quick start guides to help new users quickly familiarize themselves with basic functions.',
  bangZhuWenDangWenAnBiaoTi2:'Detailed Guide:',
  bangZhuWenDangWenAnNeiNong2:'Provide detailed operational steps for software or services to guide users through complex operations.',
  bangZhuWenDangWenAnBiaoTi3:'Issue Resolution:',
  bangZhuWenDangWenAnNeiNong3:'When users encounter issues, the FAQ section in the help document can provide solutions.',
  bangZhuWenDangWenAnBiaoTi4:'Reference Materials:',
  bangZhuWenDangWenAnNeiNong4:'Provide a complete list of functions, technical specifications, term explanations, etc., for easy user reference.',
  bangZhuWenDangWenAnBiaoTi5:'Update Notifications:',
  bangZhuWenDangWenAnNeiNong5:'Help documents inform users about software update information, including new features, improvements, and bug fixes.',
  bangZhuWenDangWenAnBiaoTi6:'Training Materials:',
  bangZhuWenDangWenAnNeiNong6:'For enterprise users, help documents can serve as training materials for onboarding new employees.',
  bangZhuWenDangWenAnBiaoTi7:'Reduce Support Costs:',
  bangZhuWenDangWenAnNeiNong7:'By providing comprehensive help documents, the demand for customer support can be reduced, thus lowering the operational costs of the enterprise.',
  bangZhuWenDangWenAnBiaoTi8:'Enhance User Satisfaction:',
  bangZhuWenDangWenAnNeiNong8:'Easy-to-access and user-friendly help documents can significantly enhance user satisfaction and loyalty.',
  bangZhuWenDangWenAnBiaoTi9:'Promote User Engagement:',
  bangZhuWenDangWenAnNeiNong9:'Through forums or community links, help documents can promote communication among users and increase user engagement.',
  bangZhuWenDangWenAnBiaoTi10:'Compliance with Standards:',
  bangZhuWenDangWenAnNeiNong10:'In China, help documents should adhere to national language and information security standards, providing content that aligns with socialist core values.',
  bangZhuWenDangJieWei:'In conclusion, help documentation is a key resource for users to learn, use, and troubleshoot, and also an important tool for enterprises to improve service quality, enhance user satisfaction, and loyalty.',
  yuFa: 'Syntax',
  shiLi:'Example',
  kaiShiRiQi:'Start date',
  jieShuRiQi:'End date',
};
