export default {
  tuiChuDengLu: 'Quit',
  geRenXinXi: 'Personal Information',
  zhiQiFuHuaQi: 'Zhiqi vue3 incubator system',
  genericTypicalPage: 'Generic typical page',
  lieBiaoYe: 'List page',
  biaoDanYe: 'Form page',
  xiangQingYe: 'Details page',
  peiZhiYe: 'Configuration page',
  daPingZiDingYi: 'Large screen customization',
  gongZuoTaiZiDingYi: 'Workbench customization',
  baoBiaoZiDingYi: 'Report customization',
  tuKeShiHuaChengXian: 'Graphic visualization',
  tuBianJiQi: 'Graph editor',
  liuChengBianPai: 'Flow choreography',
  xiTongSheZhi: 'System setting',
  zhuTiPeiZhiYe: 'Topic configuration page',
  dengLuPeiZhiYe: 'Login configuration page',
  zaiXianShengJi: 'Online upgrade',
  yongHuYinDao: 'User guidance',
  bangZhuWenDang: 'Help document',
  ruMenYinDao: 'Introductory guide',
  caiDanMingCheng:'Menu name',
  qingShuRuCaiDanMingCheng:'Please enter a menu name',
  caiDanTiXi:'Menu system',
  qingShuRuCaiDanTiXi:'Please select a menu system',
  suoShuYiJiCaiDan: 'Subordinate level menu',
  qingXuanZeSuoShuYiJiCaiDan: 'Please select the Level 1 menu',
  fangWenFangShi: 'Access mode',
  xinKaiYeMian: 'New page',
  neiQianYeMian: 'Embedded page',
  baoLiuYuanCaiDan: 'Keep the original menu',
  guanLianURL: 'Associated URL',
  qingShuRuYeMianDiZhi: 'Please enter the page address',
  caiDanGuanLianURL: 'Please enter the URL associated with the menu',
  yeMianCanShu: 'Page parameter',
  caiDanXianYinCanShu: 'Please enter the menu implicit parameters of the corresponding product',
  gongZuoTai: 'workbench',
  jiChuBiaoDan: 'Base form',
  jiChuXiangQing: 'Basic details',
  jiChuPeiZhi: 'Basic configuration',
  moRenXuanXiang1: 'Default option 1',
  moRenXuanXiang2: 'Default option 2',
  moRenXuanXiang3: 'Default option 3',
  miMaAnQuanSheZhi: 'Password security settings',
  peiZhiMiMaAnQuanYaoQiu:'Configure password security requirements to prevent weak passwords',
  zuiXiaoMiMaChangDu: 'The minimum password length is set to',
  zuiDaMiMaChangDu: 'The maximum password length is set to',
  wei:'digit',
  jianYiSheZhi: 'Suggest setting a password change every',
  tianGengHuanYiCiMiMa: 'days',
  jianYiMei3GeYueGengXinYiCi: 'Recommended to be updated every 3 months',
  tiShi: 'Tips',
  dengLuAnQuanSheZhi: 'Login security Settings',
  xianZhiYongHuDengLuFangShi: 'Limits user login failure frequency and lock mode to protect system login security',
  miaoZhiNei: 'description The number of failed login attempts within seconds exceeded',
  ciSuoDing: 'Time, lock the',
  zhangHu: 'account',
  suoDingZhangHu: 'Locked account',
  chaoShiSheZhi: 'Timeout setting',
  baoHuYongHuShuJuAnQuan: 'Protect user data security and prevent information leakage',
  fenZhongZhiNeiYongHuWuCaoZuo: 'If the user does not perform any operation within minutes, the system logs out',
  jianYi: 'Suggestion',
  ciPanChuCunSheZhi: 'Disk storage Settings',
  ziDongQingLiCiPan: 'The disk is automatically cleared to prevent disk overload',
  dangCiPanKongJianChaoGuo: 'When the disk storage space exceeds',
  shuJuJiangZiDongXunHuanFuGai: 'Data is automatically cycled over and an alarm is generated',
  shuZi: 'figure',
  ziMuDaXiaoXie: 'Letters（case）',
  teShuZiFu: 'Special character',
  jinZhiChiEXCELGeShiWenJian: 'Only EXCEL files are supported',
  moRenBiaoQian: 'Default tag',
  zaiXian: 'online',
  miaoBianAnNiu: 'Stroke button',
  zuJianLeiXing: 'Component type',
  liuLiangTanZhen: 'Flow probe(APT)',
  zhuCeShiJian: 'Registration time',
  benRiShangSongTiaoShu: 'Number of items sent today',
  weiYiBiaoShi: 'Unique identification',
  ruanJianBanBen: 'Software version',
  xuKeZheng: 'licence',
  tiao: 'article',
  zhengShi: 'Formal',
  daoQi: 'expire',
  sheBei: 'Device IP',
  guiZeBanBen: 'Rule version',
  danWei: 'unit',
  gengDuoXinXi: 'More information',
  ziChanBianHao: 'Asset number',
  shiYongZhuangTai: 'Use condition',
  shiYongZhong: 'In use',
  shiYongRen: 'user',
  miaoShuXinXi: 'Descriptive information',
  guoChanHua: 'localization',
  puTong: 'Normal',
  renWuJiLu: 'Task record',
  diZhi: 'Address',
  gaoFengXian: 'High risk',
  zhongFengXian: 'Medium risk',
  diFengXian: 'Low risk',
  yunXuFangWen: 'Allow access',
  mingLingZuDuan: 'Command blocking',
  xinJian: 'New build',
  daoChu: 'Export',
  zhongDianGuanZhu: 'Focus on',
  quXiaoGuanZhu: 'Unfollow',
  xiangQing: 'Details',
  shuRuKuangWenBen: 'Text in the input box',
  xuanZeQi: 'Selector',
  xuanZeXiang1: 'Option 1',
  xuanZeXiang2: 'Option 2',
  riQi: 'Date',
  qingXuanZe: 'Please select',
  riQiFanWei: 'Date range',
  kaiShiShiJian: 'Start time',
  jieShuShiJian: 'End time',
  xiangMuMingCheng: 'Project Name',
  suoShuZuZhi: 'Affiliated organization',
  suoShuLeiBie: 'Category',
  caoZuo: 'Operation',
  moRenXuanXiang: 'Default option',
  yiXuanXuanXiang: 'Selected options',
};
