export default {
  diSanFangXinXi: '第三方信息共享政策',
  he: '和',
  yinSiZhengCe: '隐私政策',
  tongYi: '同意',
  wangJiMiMa: '忘记密码',
  tianNeiZiDongDeng: '5天内自动登录',
  huoQuYanZhengMa: '获取验证码',
  qingShuRuYanZheng: '请输入验证码',
  biTianXiang: '必填项',
  qingShuRuMiMa: '请输入密码',
  qingShuRuYongHu: '请输入用户名',
  hangZhouAnHengXin: '杭州安恒信息技术股份有限公司',
  qingShiYongWeiXin: '请使用微信扫码登录',
  youKeZhangHaoDeng: '游客账号登录',
  anHengNeiBuYan: '安恒内部演示账号登录',
  qiTaDengLuFang: '其他登录方式',
  saoMaDengLu: '扫码登录',
  zhangHaoDengLu: '账号登录',
};
