export default {
  //ued国际化通用翻译 
  test: 'Test',
  add: 'Add',
  edit: 'Edit',
  delete: 'Delete',
  cancel: 'Cancel',
  save: 'Save',
  confirm: 'Confirm',
  close: 'Close',
  update: 'Update',
  search: 'Search',
  reset: 'Reset',
  copy: 'Copy',
  login: 'Login',
  logout: 'Quit',
  signup: 'Register',
  profile: 'Profile',
  setting: 'Setting',
  menu: 'Menu',
  home: 'Home',
  username: 'Username',
  password: 'Password',
  email: 'Email',
  phone: 'Phone',
  sex: 'Sex',
  birthday: 'Birthday',
  nickname: 'Nickname',
  remark: 'Remarks',
  status: 'Status',
  role: 'Role',
  permission: 'Permission',
  about: 'About',
  version: 'Version',
  copyright: 'Copyright',
  userManage: 'User Management',
  roleManage: 'Role Management',
  permissionManage: 'Permission Management',
  menuManage: 'Menu Management',
  logManage: 'Log Management',
  systemManage: 'System Management',
  systemConfig: 'System Configuration',
  module: 'Module',
  keyword: 'Keyword',
  pagination: 'Page',
  pageSize: 'Page Size',
  currentPage: 'Current Page',
  pageTotal: 'Page Count',
  assetManage: 'Asset Management',
  asset: 'Asset',
  assetType: 'Asset Type',
  assetCategory: 'Asset Category',
  assetStatus: 'Asset Status',
  assetList: 'Asset List',
  assetAdd: 'Add Asset',
  assetEdit: 'Edit Asset',
  assetDelete: 'Delete Asset',
  assetDetail: 'Asset Details',
  assetLog: 'Asset Log',
  report: 'Report',
  reportManage: 'Report Management',
  reportList: 'Report List',
  reportAdd: 'Add Report',
  reportEdit: 'Edit Report',
  reportDelete: 'Delete Report',
  reportDetail: 'Report Details',
  reportLog: 'Report Log',
  dashboard: 'Dashboard',
  dashboardManage: 'Dashboard Management',
  dashboardList: 'Dashboard List',
  dashboardAdd: 'Add Dashboard',
  dashboardEdit: 'Edit Dashboard',
  dashboardDelete: 'Delete Dashboard',
  dashboardDetail: 'Dashboard Details',
  dashboardLog: 'Dashboard Logs',
  return: 'Return',
  example: 'Example',
};
