export default {
  diSanFangXinXi: ' Third party information sharing policy',
  he: 'And',
  yinSiZhengCe: ' Privacy Policy ',
  tongYi: 'Agree',
  wangJiMiMa: 'Forgot password',
  tianNeiZiDongDeng: 'Automatically log in within 5 days',
  huoQuYanZhengMa: 'Verification Code',
  qingShuRuYanZheng: 'Please enter the verification code',
  biTianXiang: 'Required ',
  qingShuRuMiMa: 'Please Enter Password',
  qingShuRuYongHu: 'Please Enter Username',
  hangZhouAnHengXin: 'Hangzhou Anheng Information Technology Co., Ltd',
  qingShiYongWeiXin: 'Please use WeChat to scan and log in',
  youKeZhangHaoDeng: 'Visitor login',
  anHengNeiBuYan: 'Internal demonstration account login',
  qiTaDengLuFang: 'Other login methods',
  saoMaDengLu: 'Scan Login',
  zhangHaoDengLu: 'Account Login'
};
